"use client";

import Link from "next/link";
import styles from "./HandoverGuide.module.css";

const ADMIN_SURFACES = [
  ["Satışlar", "/admin", "Sipariş, müşteri, ödeme, aktivasyon ve kurumsal hesap operasyonları."],
  ["Operasyon", "/admin/operations", "Baskı/kargo, Network Mail, lisans batchleri, fiyatlandırma ve audit log."],
  ["Yönetici Erişimi", "/admin/access", "Super Admin yetkisi verme ve eski yöneticinin yetkisini kaldırma."],
  ["Güvenlik", "/admin/security", "Google Authenticator kurulumu ve AAL2 doğrulaması."],
] as const;

export default function AdminHandoverGuidePage() {
  return <main className={styles.page} id="main-content">
    <section className={styles.shell}>
      <div className={styles.toolbar}>
        <div><span className={styles.kicker}>SUPER ADMIN DEVİR DOKÜMANI</span><h1>Yenomi ID Kullanım ve Devir Rehberi</h1><p>Yeni yöneticiye sistemin nasıl çalıştığını, hangi ekranın ne için kullanıldığını ve kritik güvenlik kurallarını aktarmak için hazırlanmıştır.</p></div>
        <div className={styles.actions}><Link href="/admin">Satış merkezine dön</Link><button type="button" onClick={() => window.print()}>PDF Olarak Kaydet</button></div>
      </div>

      <div className={styles.warning}><strong>Bu dokümana gizli bilgi yazmayın.</strong><span>Şifre, Supabase service-role key, iyzico anahtarı, e-posta parolası, Google Authenticator QR kodu/TOTP secret'ı ve kişisel erişim tokenları PDF'e eklenmemelidir.</span></div>

      <section className={styles.section}><h2>1. Super Admin erişimi</h2><p>Super Admin için ayrı bir herkese açık giriş ekranı yoktur. Yönetici normal giriş ekranından oturum açar; sistem kullanıcının <code>admin_users</code> kaydını kontrol eder. Super Admin API işlemleri Google Authenticator ile AAL2 doğrulaması yapılmadan çalışmaz.</p><div className={styles.steps}><div><b>1</b><span><strong>/giris</strong><small>Normal kullanıcı girişi yapılır.</small></span></div><div><b>2</b><span><strong>/admin/security</strong><small>Google Authenticator kodu ile ikinci faktör doğrulanır.</small></span></div><div><b>3</b><span><strong>/admin</strong><small>Satış ve hesap operasyonları yönetilir.</small></span></div></div></section>

      <section className={styles.section}><h2>2. Super Admin ekran haritası</h2><p>Panelde yapılabilen yönetici işlemlerinin tek kaynak haritası aşağıdadır. Bir operasyon bu tabloda yoksa panelde varmış gibi kabul edilmemelidir.</p><table><thead><tr><th>Ekran</th><th>Adres</th><th>Ne yapılır?</th></tr></thead><tbody>{ADMIN_SURFACES.map(([label, href, description]) => <tr key={href}><td><Link href={href}>{label}</Link></td><td><code>{href}</code></td><td>{description}</td></tr>)}</tbody></table></section>

      <section className={styles.section}><h2>3. Satış Merkezi — /admin</h2><p>Bireysel ve kurumsal tüm satın almalar aynı ticari görünümde izlenir. Sipariş, müşteri, ürün, ödeme, aktivasyon ve fulfillment durumları birbirinden ayrı değerlendirilmelidir.</p><table><thead><tr><th>Alan</th><th>Ne için kullanılır?</th></tr></thead><tbody><tr><td>Tüm Satışlar</td><td>Bireysel ve kurumsal siparişlerin tek listede takibi.</td></tr><tr><td>Ödeme Mutabakatı</td><td>iyzico ödeme sonucu ile sipariş/entitlement kayıtlarının tutarlı olup olmadığını kontrol eder.</td></tr><tr><td>Kurumsal Hesaplar</td><td>Şirket tenant'ı, yönetici bağlantısı, kapasite ve abonelik görünümü.</td></tr><tr><td>Filtreler</td><td>Bireysel/kurumsal, ürün tipi, operasyon aşaması ve sipariş durumu ayrımı.</td></tr></tbody></table></section>

      <section className={styles.section}><h2>4. Operasyon Merkezi — /admin/operations</h2><table><thead><tr><th>Sekme</th><th>Görev</th></tr></thead><tbody><tr><td>Baskı & Kargo</td><td>Ödenmiş fiziksel kartın baskı kuyruğu, baskı onayı, kargo firması/takip no ve teslimat aşamaları.</td></tr><tr><td>Network Mail</td><td>Premium kullanıcıların kredi kotasını ve yetkili manuel düzeltmeleri yönetir.</td></tr><tr><td>Lisans Batchleri</td><td>Kurumsal ana paket ve sonradan alınan ek kapasiteleri ayrı satın alma/yenileme dönemleriyle izler.</td></tr><tr><td>Fiyatlandırma</td><td>Aktif ürün ve kurumsal paket fiyatlarını yönetir.</td></tr><tr><td>Audit Log</td><td>Yönetici aksiyonlarının zaman damgalı denetim geçmişini gösterir.</td></tr></tbody></table></section>

      <section className={styles.section}><h2>5. Yönetici Erişimi — /admin/access</h2><p>Devir sırasında Super Admin yetkisi bu ekrandan yönetilir. Yeni yönetici önce normal Yenomi hesabını oluşturur; mevcut AAL2 doğrulamalı Super Admin, kullanıcının e-postasını kullanarak yetki verir. Yeni yönetici kendi oturumunda <Link href="/admin/security">Güvenlik</Link> ekranından kendi Google Authenticator faktörünü kurar.</p><ul><li>Şifre veya TOTP secret paylaşılmaz.</li><li>Kendi Super Admin yetkinizi aynı oturumdan kaldıramazsınız.</li><li>Sistemde son kalan Super Admin silinemez.</li><li>Yetki verme ve kaldırma işlemleri audit log'a yazılır.</li><li>Eski yöneticinin yetkisi ancak yeni yöneticinin AAL2 erişimi doğrulandıktan sonra kaldırılır.</li></ul></section>

      <section className={styles.section}><h2>6. Fiziksel kart iş akışı</h2><div className={styles.flow}><span>Ödeme alındı</span><i>→</i><span>Profil tamamlandı</span><i>→</i><span>PRINT_PENDING</span><i>→</i><span>PRINTING</span><i>→</i><span>SHIPPING_PENDING</span><i>→</i><span>IN_TRANSIT</span><i>→</i><span>OUT_FOR_DELIVERY</span><i>→</i><span>DELIVERED</span></div><p>Profil tamamlanması tek başına ücretsiz kart hakkı oluşturmaz. Baskıya yalnızca mevcut ödenmiş/yetkili fiziksel kart birimi geçebilir.</p></section>

      <section className={styles.section}><h2>7. Bireysel paket mantığı</h2><table><thead><tr><th>Paket/işlem</th><th>Operasyonel not</th></tr></thead><tbody><tr><td>Standard</td><td>Temel bireysel ürün. Güncel fiyat katalog kaynağından okunmalıdır.</td></tr><tr><td>Premium</td><td>Premium hakları ve Network Mail kredisi içerir.</td></tr><tr><td>Premium yükseltme</td><td>Standard kullanıcının Premium entitlement'a geçişidir; yeni fiziksel kart varsayılmamalıdır.</td></tr><tr><td>Yenileme</td><td>Hizmet dönemi yenilemesi fiziksel kart üretimiyle eş anlamlı değildir.</td></tr></tbody></table></section>

      <section className={styles.section}><h2>8. Kurumsal satın alma ve kapasite</h2><p>Kurumsal kapasite tek bir toplam sayaç gibi faturalandırılmaz. Her satın alma bir batch/term olarak korunur. Örneğin ana paket + daha sonra ek kapasite alımı iki farklı satın alma ve iki farklı yenileme tarihi olabilir.</p><ul><li>Batch ID ve kaynak sipariş korunur.</li><li>Başlangıç ve bitiş tarihi batch bazındadır.</li><li>Yenileme bedeli batch bazındadır.</li><li>Toplam kapasite yalnızca kullanım görünümü için birleştirilebilir.</li><li>Otomatik yenileme kaydı oluşturmak otomatik kart çekimi anlamına gelmez; ödeme mandate'i yoksa karttan otomatik tahsilat yapılmaz.</li></ul></section>

      <section className={styles.section}><h2>9. Network Mail ve fiyatlandırma</h2><p>Kredi yalnızca doğrulanmış başarılı/idempotent gönderim sınırında tüketilmelidir; başarısız gönderim kredi harcamamalıdır. Super Admin manuel düzeltme yaptığında neden alanı doldurmalı ve işlem audit log'a yazılmalıdır.</p><p>Fiyat değişiklikleri kullanıcı arayüzünde sabit metinlerle çoğaltılmamalıdır. Operasyon Merkezi içindeki fiyat kataloğu kaynak kabul edilir; değişiklik sonrası checkout, ürün sayfası ve kurumsal plan görünümü birlikte doğrulanmalıdır.</p></section>

      <section className={styles.section}><h2>10. Panel dışındaki devir işlemleri</h2><p>Aşağıdaki sistemlerin erişimi Yenomi Super Admin panelinden yönetilmez. Bunlar ilgili sağlayıcının kendi yönetim konsolunda ayrıca devredilmelidir.</p><table><thead><tr><th>Sistem</th><th>Devir yöntemi</th></tr></thead><tbody><tr><td>Supabase</td><td>Proje/organizasyon üyeliği ve kişiye özel erişim.</td></tr><tr><td>Vercel</td><td>Team/project üyeliği ve deployment yetkileri.</td></tr><tr><td>GitHub</td><td>Repository erişimi ve gerekli branch/review yetkileri.</td></tr><tr><td>iyzico</td><td>Merchant panel kullanıcı/yetki devri.</td></tr><tr><td>Resend</td><td>Hesap/domain/API yönetim yetkisi.</td></tr><tr><td>Alan adı/DNS</td><td>Registrar ve DNS sağlayıcısında ayrı kullanıcı erişimi.</td></tr></tbody></table><p>Production secret'ları yeni yöneticiye mesaj/PDF ile iletmek yerine mümkün olan sistemlerde kullanıcı üyeliği verin; gerekiyorsa secret rotasyonu ayrı güvenlik işlemi olarak yapılmalıdır.</p></section>

      <section className={styles.section}><h2>11. Devir kontrol listesi</h2><div className={styles.checklist}><label><input type="checkbox" /> Yeni yöneticinin normal hesabı oluşturuldu</label><label><input type="checkbox" /> /admin/access üzerinden Super Admin yetkisi tanımlandı</label><label><input type="checkbox" /> Yeni yönetici kendi cihazında Google Authenticator kurdu ve AAL2 doğrulandı</label><label><input type="checkbox" /> Satış Merkezi ve Operasyon Merkezi yeni hesapla test edildi</label><label><input type="checkbox" /> Audit Log'da yetki verme kaydı doğrulandı</label><label><input type="checkbox" /> Eski yöneticinin Super Admin yetkisi kaldırıldı</label><label><input type="checkbox" /> Supabase, Vercel, GitHub, iyzico, Resend ve DNS erişimleri ayrıca devredildi</label><label><input type="checkbox" /> Eski kullanıcının artık gerekmeyen dış sistem erişimleri kaldırıldı</label><label><input type="checkbox" /> Üretim secret'larının hiçbiri PDF'e eklenmedi</label></div></section>

      <footer className={styles.footer}><span>Yenomi ID — Super Admin Kullanım ve Devir Rehberi</span><span>Bu çıktı operasyonel bilgilendirme dokümanıdır; gizli erişim bilgisi içermez.</span></footer>
    </section>
  </main>;
}
