"use client";

import Link from "next/link";
import styles from "./HandoverGuide.module.css";

export default function AdminHandoverGuidePage() {
  return <main className={styles.page} id="main-content">
    <section className={styles.shell}>
      <div className={styles.toolbar}>
        <div><span className={styles.kicker}>SUPER ADMIN DEVİR DOKÜMANI</span><h1>Yenomi ID Kullanım ve Devir Rehberi</h1><p>Bu rehber yalnız açıklama değildir; her adımı Yenomi ID panelindeki gerçek yönetim ekranıyla eşleştirir ve panel dışındaki sağlayıcı devirlerini ayrıca belirtir.</p></div>
        <div className={styles.actions}><Link href="/admin/access">Yönetici erişimine git</Link><button type="button" onClick={() => window.print()}>PDF Olarak Kaydet</button></div>
      </div>

      <div className={styles.warning}><strong>Bu dokümana gizli bilgi yazmayın.</strong><span>Şifre, Supabase service-role key, iyzico anahtarı, e-posta parolası, Google Authenticator QR kodu/TOTP secret'ı ve kişisel erişim tokenları PDF'e eklenmemelidir.</span></div>

      <section className={styles.section}><h2>1. Super Admin erişimi</h2><p>Super Admin için ayrı bir herkese açık giriş ekranı yoktur. Yönetici normal giriş ekranından oturum açar; sistem <code>admin_users</code> kaydını kontrol eder. Normal Super Admin API işlemleri Google Authenticator ile AAL2 doğrulanmadan çalışmaz.</p><div className={styles.steps}><div><b>1</b><span><strong>/giris</strong><small>Yönetici kendi normal Yenomi hesabıyla giriş yapar.</small></span></div><div><b>2</b><span><strong>/admin/security</strong><small>Kendi Google Authenticator faktörünü kurar ve AAL2 doğrular.</small></span></div><div><b>3</b><span><strong>/admin</strong><small>Satış, hesap ve kurumsal operasyonlara erişir.</small></span></div></div></section>

      <section className={styles.section}><h2>2. Panelde ne nereden yapılır?</h2><table><thead><tr><th>Ekran</th><th>Gerçek görev</th></tr></thead><tbody><tr><td><Link href="/admin">/admin</Link></td><td>Satış kuyruğu, ödeme mutabakatı, sipariş detayları ve kurumsal hesap yönetimi.</td></tr><tr><td><Link href="/admin/operations">/admin/operations</Link></td><td>Baskı-kargo, Network Mail, lisans batchleri, fiyatlandırma ve audit log.</td></tr><tr><td><Link href="/admin/access">/admin/access</Link></td><td>Mevcut Yenomi kullanıcısına Super Admin yetkisi verme ve eski yöneticinin yetkisini kaldırma.</td></tr><tr><td><Link href="/admin/security">/admin/security</Link></td><td>Yöneticinin kendi MFA/TOTP faktörünü kurması ve AAL2 doğrulaması.</td></tr><tr><td><Link href="/admin/devir-rehberi">/admin/devir-rehberi</Link></td><td>Devir sırası, operasyon kuralları ve kontrol listesi.</td></tr></tbody></table></section>

      <section className={styles.section}><h2>3. Satış Merkezi — /admin</h2><p>Bireysel ve kurumsal satın almalar aynı ticari görünümde izlenir. Sipariş, ödeme, aktivasyon ve fulfillment birbirinden ayrı durumlar olarak değerlendirilmelidir.</p><table><thead><tr><th>Alan</th><th>Ne için kullanılır?</th></tr></thead><tbody><tr><td>Satış Kuyruğu</td><td>Bireysel ve kurumsal siparişlerin tek listede takibi ve sipariş aksiyonları.</td></tr><tr><td>Ödeme Mutabakatı</td><td>iyzico sonucu ile sipariş/entitlement kayıtlarının tutarlı olup olmadığını kontrol eder.</td></tr><tr><td>Kurumsal Hesaplar</td><td>Şirket tenant'ı, yönetici bağlantısı, kapasite ve abonelik görünümü.</td></tr><tr><td>Filtreler</td><td>Bireysel/kurumsal, ürün tipi, operasyon aşaması ve sipariş durumu ayrımı.</td></tr></tbody></table></section>

      <section className={styles.section}><h2>4. Operasyon Merkezi — /admin/operations</h2><table><thead><tr><th>Sekme</th><th>Görev</th></tr></thead><tbody><tr><td>Baskı & Kargo</td><td>Ödenmiş fiziksel kartın baskı kuyruğu, baskı onayı, kargo firması/takip no ve teslimat aşamaları.</td></tr><tr><td>Network Mail</td><td>Premium kullanıcı kotası ve yetkili manuel düzeltmeler.</td></tr><tr><td>Lisans Batchleri</td><td>Kurumsal ana paket ve sonradan alınan ek kapasiteleri ayrı satın alma/yenileme dönemleriyle izler.</td></tr><tr><td>Fiyatlandırma</td><td>Aktif ürün ve kurumsal paket fiyatlarını katalog kaynağından yönetir.</td></tr><tr><td>Audit Log</td><td>Yönetici aksiyonlarının zaman damgalı denetim geçmişini gösterir.</td></tr></tbody></table></section>

      <section className={styles.section}><h2>5. Fiziksel kart iş akışı</h2><div className={styles.flow}><span>Ödeme alındı</span><i>→</i><span>Profil tamamlandı</span><i>→</i><span>PRINT_PENDING</span><i>→</i><span>PRINTING</span><i>→</i><span>SHIPPING_PENDING</span><i>→</i><span>IN_TRANSIT</span><i>→</i><span>OUT_FOR_DELIVERY</span><i>→</i><span>DELIVERED</span></div><p>Profil tamamlanması tek başına ücretsiz kart hakkı oluşturmaz. Baskıya yalnızca mevcut ödenmiş/yetkili fiziksel kart birimi geçebilir.</p></section>

      <section className={styles.section}><h2>6. Bireysel paket mantığı</h2><table><thead><tr><th>Paket/işlem</th><th>Operasyonel not</th></tr></thead><tbody><tr><td>Standard</td><td>Temel bireysel ürün. Güncel fiyat için katalog değeri kaynak kabul edilir.</td></tr><tr><td>Premium</td><td>Premium hakları ve tanımlı Network Mail kotasını içerir.</td></tr><tr><td>Premium yükseltme</td><td>Standard kullanıcının Premium entitlement'a geçişidir; yeni fiziksel kart varsayılmamalıdır.</td></tr><tr><td>Yenileme</td><td>Hizmet dönemi yenilenir; yenileme fiziksel kart üretimiyle eş anlamlı değildir.</td></tr></tbody></table></section>

      <section className={styles.section}><h2>7. Kurumsal satın alma ve kapasite</h2><p>Kurumsal kapasite tek bir toplam sayaç gibi faturalandırılmaz. Her satın alma ayrı batch/term olarak korunur. Ana paket ve daha sonra alınan ek kapasite farklı satın alma ve yenileme tarihlerine sahip olabilir.</p><ul><li>Batch ID ve kaynak sipariş korunur.</li><li>Başlangıç ve bitiş tarihi batch bazındadır.</li><li>Yenileme bedeli batch bazındadır.</li><li>Toplam kapasite yalnız kullanım görünümü için birleştirilebilir.</li><li>Yenileme kaydı oluşturmak otomatik kart çekimi anlamına gelmez; ödeme mandate'i yoksa otomatik tahsilat varsayılmaz.</li></ul></section>

      <section className={styles.section}><h2>8. Network Mail ve fiyatlandırma</h2><p>Network Mail kredisi yalnız başarılı/idempotent gönderim sınırında tüketilmelidir. Manuel artış veya reset nedeni belirtilmeli ve audit log'a yazılmalıdır. Fiyat değişikliklerinde Super Admin fiyatlandırma ekranındaki katalog değerleri kaynak kabul edilir; checkout, ürün ve kurumsal plan görünümü birlikte doğrulanır.</p></section>

      <section className={styles.section}><h2>9. Güvenlik ve Super Admin devri</h2><ol><li>Yeni yönetici için normal Yenomi hesabı oluşturulur.</li><li><Link href="/admin/access">Yönetici Erişimi</Link> ekranından Super Admin yetkisi verilir.</li><li>Yeni yönetici kendi hesabıyla giriş yapar ve <Link href="/admin/security">Güvenlik</Link> ekranından kendi Authenticator faktörünü kurar.</li><li>Satış ve Operasyon ekranlarında erişim test edilir.</li><li>Eski yöneticinin Super Admin yetkisi <Link href="/admin/access">Yönetici Erişimi</Link> ekranından kaldırılır.</li><li>Audit Log üzerinden grant/revoke ve kritik operasyon kayıtları kontrol edilir.</li></ol><ul><li>Şifre veya TOTP secret hiçbir aşamada paylaşılmaz.</li><li>Kendi Super Admin yetkinizi aynı oturumdan kaldıramazsınız.</li><li>Sistemde son kalan Super Admin kaydı silinemez.</li><li>Eski yöneticinin yetkisi, yeni yöneticinin AAL2 erişimi doğrulanmadan kaldırılmamalıdır.</li><li>Yetki verme ve kaldırma işlemleri audit log üzerinden doğrulanmalıdır.</li></ul></section>

      <section className={styles.section}><h2>10. Panel dışı erişimler</h2><p>Aşağıdaki yetkiler Yenomi ID Super Admin panelinden yönetilmez. Devir sırasında ilgili sağlayıcının kendi yönetim ekranında ayrıca ele alınmalıdır.</p><table><thead><tr><th>Sistem</th><th>Devir kuralı</th></tr></thead><tbody><tr><td>GitHub</td><td>Repository/organization erişimi kişiye özel hesapla verilir, eski kullanıcının erişimi kaldırılır.</td></tr><tr><td>Vercel</td><td>Team/project erişimi yeni yöneticiye atanır; production environment secret'ları mesajla paylaşılmaz.</td></tr><tr><td>Supabase</td><td>Project/team erişimi ayrı kullanıcıya verilir; service-role key paylaşımı yapılmaz.</td></tr><tr><td>iyzico</td><td>Merchant panel yetkileri sağlayıcı panelinden devredilir.</td></tr><tr><td>Resend / e-posta</td><td>Hesap/alan adı erişimleri sağlayıcı tarafından yönetilir.</td></tr><tr><td>Domain / DNS</td><td>Registrar ve DNS sağlayıcısı erişimi ayrıca devredilir.</td></tr></tbody></table></section>

      <section className={styles.section}><h2>11. Devir kontrol listesi</h2><div className={styles.checklist}><label><input type="checkbox" /> Yeni yöneticinin normal hesabı oluşturuldu</label><label><input type="checkbox" /> /admin/access üzerinden Super Admin yetkisi tanımlandı</label><label><input type="checkbox" /> Google Authenticator yeni yöneticinin kendi cihazında kuruldu ve AAL2 doğrulandı</label><label><input type="checkbox" /> Satış Merkezi ve Operasyon Merkezi test edildi</label><label><input type="checkbox" /> Eski yöneticinin Super Admin yetkisi kaldırıldı</label><label><input type="checkbox" /> GitHub, Vercel, Supabase, iyzico, Resend ve domain erişimleri ayrı ayrı kontrol edildi</label><label><input type="checkbox" /> Baskı/kargo örnek akışı kontrol edildi</label><label><input type="checkbox" /> Kurumsal batch ve yenileme kayıtları kontrol edildi</label><label><input type="checkbox" /> Network Mail kotası ve audit kayıtları kontrol edildi</label><label><input type="checkbox" /> Üretim secret'larının hiçbiri PDF'e eklenmedi</label></div></section>

      <footer className={styles.footer}><span>Yenomi ID — Super Admin Kullanım ve Devir Rehberi</span><span>Bu çıktı operasyonel bilgilendirme dokümanıdır; gizli erişim bilgisi içermez.</span></footer>
    </section>
  </main>;
}
