import type { Metadata } from "next";
import Link from "next/link";
import { formatTryFromKurus } from "../lib/config/product";
import { CORPORATE_PACKAGE_LADDER, INDIVIDUAL_PLAN, INDIVIDUAL_PREMIUM_PLAN } from "../lib/commerce/packages";
import { Icon } from "./icons";
import { YenomiProductVisual } from "./ui/YenomiProductVisual";

export const metadata: Metadata = { title: "Yenomi ID | Kartvizitin güncel kalsın", description: "NFC + QR dijital kartvizit, networking araçları ve Network Mail. Kartın aynı kalır; profilin güncellenir, tanışmalarını takip edersin.", alternates: { canonical: "/" } };
const individualPrice = formatTryFromKurus(INDIVIDUAL_PLAN.priceKurus);
const premiumPrice = formatTryFromKurus(INDIVIDUAL_PREMIUM_PLAN.priceKurus);
const corporateEntryPrice = formatTryFromKurus(CORPORATE_PACKAGE_LADDER[0].priceKurus);
const heroTrust = ["Türkiye içi kargo dahil", "2 iş gününde hazırlanır", "Uygulama gerekmez", "KAYIP MODU · Kaybolursa erişimi kapat"];
const packageComparisonRows = [
  ["Fiyat", individualPrice, premiumPrice, `${corporateEntryPrice}’dan başlar`],
  ["En uygun kullanım", "Dijital kartvizit paylaşımı", "Networking ve satış takibi", "Çalışan ve kart yönetimi"],
  ["NFC + QR kart", "included", "included", "Kişi sayısı kadar"],
  ["Kişi / lead toplama", "unavailable", "included", "included"],
  ["Toplantı ve sunum", "unavailable", "included", "included"],
  ["Follow-up e-posta", "—", "500 Network Mail", "Kişi başı 100 Network Mail"],
  ["Merkezi çalışan yönetimi", "unavailable", "unavailable", "included"],
  ["Rol, departman ve durum", "unavailable", "unavailable", "included"],
  ["Kurumsal marka standardı", "unavailable", "unavailable", "included"],
] as const;
function PackageComparisonValue({ value }: { value: string }) {
  if (value === "included") {
    return <span className="home-package-matrix__availability is-included"><Icon name="check" /><span className="sr-only">Dahil</span></span>;
  }
  if (value === "unavailable") {
    return <span className="home-package-matrix__availability is-unavailable"><span aria-hidden="true">—</span><span className="sr-only">Yok</span></span>;
  }
  return <>{value}</>;
}

const comparisonRows = [["Bilgilerin değişti", "Yeniden baskı gerekir", "Profili anında güncellersin"],["Paylaşım", "Basılı bilgilerle sınırlı", "NFC + QR + canlı profil"],["Kart kayboldu", "Kontrol sende değildir", "Kayıp moduyla erişimi kapatırsın"],["İletişim kaydı", "Manuel giriş gerekir", "Tek dokunuşla rehbere kaydet"]] as const;
const faqItems = [["Premium ne ekliyor?", "Premium; NFC + QR kart ve canlı profile ek olarak toplantı, sunum, kişi yönetimi ve 500 Network Mail kredisi içerir. Tanışma sonrasındaki takip akışını tek üründe toplar."],["Uygulama indirmek gerekiyor mu?", "Hayır. NFC veya QR ile profil tarayıcıda doğrudan açılır."],["Bilgilerim değişirse kartı yeniden bastırır mıyım?", "Hayır. Fiziksel kart aynı kalır; profilindeki bilgileri güncellersin."],["Kartımı kaybedersem ne olur?", "Kart erişimini panelden kapatabilir, kayıp moduyla kontrolü koruyabilirsin."],["NFC kullanılmazsa ne olur?", "Kart üzerindeki QR kod aynı profile bağlıdır; QR ile de profil açılır."],["Ödeme kartı bilgilerim Yenomi’de tutuluyor mu?", "Hayır. Kart bilgileri Yenomi’de saklanmaz; ödeme iyzico altyapısı üzerinden gerçekleşir."]] as const;

export default function HomePage() { return <div className="home-mockup home-premium home-premium--hero-v2"><main id="main-content">
<section className="home-mockup__hero home-premium__hero-v2 home-sales-hero" aria-labelledby="home-title"><div className="home-mockup__copy home-sales-copy"><span className="home-premium__hero-pill"><i aria-hidden="true" /> YENOMI ID PREMIUM · NFC + QR</span><h1 id="home-title">Bir kez basılır.<br /><span>Tanışma orada bitmez.</span></h1><p>Kartını paylaş, yeni bağlantını kaydet ve tanışma sonrasındaki takibi tek yerden sürdür.</p><div className="home-mockup__actions home-premium__hero-actions home-sales-actions"><Link className="home-mockup__button home-mockup__button--gold home-mockup__button--primary" href="/urunler/nfc-kart?paket=premium">Premium’u Al <span aria-hidden>→</span></Link><Link className="home-premium__hero-secondary" href="#paths-title">Paketleri karşılaştır <span aria-hidden>↓</span></Link></div><div className="home-sales-offer"><strong>{premiumPrice} · ilk yıl dahil</strong><span>NFC + QR kart · kişi yönetimi · 500 Network Mail</span></div><div className="home-premium__hero-trust home-sales-trust">{heroTrust.map((item)=><span key={item}><Icon name="check" />{item}</span>)}</div></div><div className="home-sales-stage" aria-label="Yenomi ID Premium ürün görseli"><div className="home-sales-stage-label" aria-hidden="true">PREMIUM · NFC + QR · CANLI PROFİL</div><div className="home-sales-stage-glow" aria-hidden="true" /><div className="home-hero-specimens"><YenomiProductVisual variant="card" finish="matte" /><YenomiProductVisual variant="profile" compact /></div><div className="home-sales-capabilities" aria-hidden="true"><span>NFC</span><span>QR</span><span>Network Mail</span></div></div></section>
<section className="home-premium__proof" aria-labelledby="proof-title"><div className="home-premium__proof-head"><span className="home-mockup__kicker">GÜVENİLİR VE KOLAY</span><h2 id="proof-title">Paylaşmak için uygulama gerekmez.</h2><p>NFC veya QR ile profil doğrudan açılır. Kartın 2 iş gününde hazırlanır ve ödeme iyzico üzerinden güvenle tamamlanır.</p></div><div className="home-premium__principles"><article><span>01</span><div><strong>Hızlı hazırlık</strong><p>Kartın 2 iş günü içinde kargoya hazırlanır.</p></div></article><article><span>02</span><div><strong>Uygulamasız paylaşım</strong><p>NFC veya QR ile dijital kartvizitin tarayıcıda açılır.</p></div></article><article><span>03</span><div><strong>Premium takip</strong><p>Tanıştığın kişiyi kaydet ve Network Mail ile iletişimi sürdür.</p></div></article></div></section>
<section className="home-package-matrix" aria-labelledby="paths-title"><div className="home-package-matrix__head"><span className="home-mockup__kicker">BİREYSEL · PREMIUM · KURUMSAL</span><h2 id="paths-title">Hangisi sana uygun?</h2><p>Bireysel kartvizit paylaşımı için; Premium networking ve takip için; Kurumsal ekip yönetimi için.</p></div><div className="home-package-matrix__scroll" role="region" aria-label="Paket karşılaştırma tablosu" tabIndex={0}><div className="home-package-matrix__table" role="table" aria-label="Paket karşılaştırması"><div className="home-package-matrix__row home-package-matrix__header" role="row"><span role="columnheader" aria-label="Özellik" /><strong role="columnheader">Bireysel</strong><strong role="columnheader">Premium</strong><strong role="columnheader">Kurumsal</strong></div>{packageComparisonRows.map(([label,a,b,c])=><div className="home-package-matrix__row" role="row" key={label}><strong role="rowheader">{label}</strong><span role="cell"><PackageComparisonValue value={a} /></span><span role="cell"><PackageComparisonValue value={b} /></span><span role="cell"><PackageComparisonValue value={c} /></span></div>)}<div className="home-package-matrix__row home-package-matrix__actions" role="row"><span role="rowheader">Seç</span><span role="cell"><Link href="/urunler/nfc-kart?paket=individual">Bireysel’i İncele →</Link></span><span role="cell"><Link href="/urunler/nfc-kart?paket=premium">Premium’u Seç →</Link></span><span role="cell"><Link href="/kurumsal">Kurumsal Paketler →</Link></span></div></div></div></section>
<section id="nasil-calisir" className="home-premium__journey" aria-labelledby="how-it-works-title"><div className="home-premium__journey-head"><span className="home-mockup__kicker">NASIL ÇALIŞIR</span><h2 id="how-it-works-title">Paylaş. Kaydet. Takip et.</h2><p>Premium, kartvizit paylaşımından tanışma sonrasındaki profesyonel takibe kadar tek akış sunar.</p></div><ol className="home-premium__journey-steps"><li><span>01</span><div><h3>Paylaş</h3><p>NFC veya QR ile güncel dijital kartvizitini aç.</p></div></li><li><span>02</span><div><h3>Bağlantıyı kaydet</h3><p>Tanıştığın kişileri ve görüşmelerini tek yerde tut.</p></div></li><li><span>03</span><div><h3>Takip et</h3><p>Network Mail ile görüşme sonrası iletişimi sürdür.</p></div></li></ol><div className="home-premium__journey-action"><p><strong><Link href="/nasil-calisir">Nasıl çalıştığını detaylı gör →</Link></strong></p></div></section>
<section className="home-sales-comparison" aria-labelledby="comparison-title"><div className="home-sales-comparison-head"><span className="home-mockup__kicker">NEDEN YENOMI ID?</span><h2 id="comparison-title">Kart aynı kalır.<br />Profil güncel kalır.</h2></div><div className="home-sales-comparison-table" role="table" aria-label="Klasik kartvizit ve Yenomi ID karşılaştırması" tabIndex={0}> <div className="home-sales-comparison-header" role="row"><span>Durum</span><span>Klasik kartvizit</span><span>Yenomi ID</span></div>{comparisonRows.map(([a,b,c])=><div className="home-sales-comparison-row" role="row" key={a}><strong>{a}</strong><span>{b}</span><span><Icon name="check" />{c}</span></div>)}</div></section>
<section className="home-sales-faq" aria-labelledby="faq-title"><div className="home-sales-faq-intro"><span className="home-mockup__kicker">SIK SORULANLAR</span><h2 id="faq-title">Satın almadan önce bilmen gerekenler.</h2></div><div className="home-sales-faq-list">{faqItems.map(([q,a],i)=><details className="home-sales-faq-item" key={q} open={i===0}><summary><span>{q}</span><i aria-hidden="true">+</i></summary><p>{a}</p></details>)}</div><div className="home-sales-support"><Link href="/destek">Yardım merkezine git →</Link></div></section>
<section className="home-premium__final home-sales-final" aria-labelledby="final-title"><span className="home-mockup__kicker">ÖNERİLEN · PREMIUM</span><h2 id="final-title">Tanışma kartvizitte bitmesin.</h2><p>NFC + QR kartvizit, kişi yönetimi ve 500 Network Mail tek pakette.</p><div className="home-sales-final-offer"><strong>{premiumPrice}</strong><span>1 kart · ilk yıl platform erişimi · 500 Network Mail · kargo dahil</span></div><div className="home-mockup__actions"><Link className="home-mockup__button home-mockup__button--gold" href="/urunler/nfc-kart?paket=premium">Premium’u Seç <span aria-hidden>→</span></Link></div></section>
</main><aside className="home-sales-mobile-cta" aria-label="Premium hızlı satın alma"><div className="home-sales-mobile-cta__copy"><span>ÖNERİLEN · PREMIUM</span><strong>{premiumPrice} · ilk yıl dahil</strong></div><Link className="home-mockup__button home-mockup__button--gold" href="/urunler/nfc-kart?paket=premium">Premium’u Seç</Link></aside></div>; }
